#!/usr/bin/env bash
# devkit-toolkit: shared Claude subagent generation
# Sourced by adapters/claude/generate (stack subagents, per-project) and
# bin/devkit-install (core subagents, global ~/.claude/agents).
#
# Requires: jq, resolve.sh already sourced (for _build_plugin_index inputs).
#
# Exports:
#   DEVKIT_AGENT_SENTINEL  — marker comment placed below frontmatter in generated files
#   reap_devkit_agents     — remove only devkit-generated agent files in a dir
#   emit_subagent          — write one .claude agent file from a SKILL.md (if claudeSubagent)
#   generate_subagents     — emit agents for a given set of plugin names

# Sentinel lives *below* the frontmatter (not line 1): Claude Code's frontmatter
# parser requires the opening `---` on line 1, and a leading non-`---` line
# silently breaks subagent auto-discovery in `claude -p`.
DEVKIT_AGENT_SENTINEL="<!-- devkit-managed: regenerated by devkit (do not edit) -->"

# Shared prefix of every sentinel devkit has ever written. Reaping matches on the
# prefix (not the full string) so agent files from older adapter versions — which
# used a different trailing message — are still cleaned up during migration.
DEVKIT_AGENT_SENTINEL_PREFIX="<!-- devkit-managed:"

# reap_devkit_agents <agents_dir>
# Delete only files carrying a devkit sentinel; leaves user-authored agents alone.
reap_devkit_agents() {
  local agents_dir="$1"
  [ -d "$agents_dir" ] || return 0
  local f
  for f in "$agents_dir"/*.md; do
    [ -f "$f" ] || continue
    if grep -qF "$DEVKIT_AGENT_SENTINEL_PREFIX" "$f" 2>/dev/null; then
      rm -f "$f"
    fi
  done
}

# emit_subagent <skill_file> <agents_dir>
# Writes <agents_dir>/<name>.md when the skill has `claudeSubagent: true`.
# Prints the emitted agent name (empty if skipped).
emit_subagent() {
  local skill_file="$1"
  local agents_dir="$2"
  awk -v sentinel="$DEVKIT_AGENT_SENTINEL" -v out_dir="$agents_dir" '
    BEGIN { depth=0; in_fm=0; subagent=0; collecting=""; cont="" }
    /^---[[:space:]]*$/ {
      depth++
      if (depth==1) { in_fm=1; next }
      if (depth==2) { in_fm=0; next }
    }
    in_fm && collecting != "" {
      if ($0 ~ /^[A-Za-z_][A-Za-z0-9_]*:/) {
        meta[collecting]=cont
        collecting=""; cont=""
        # fall through to process this line as a new key
      } else {
        line=$0
        sub(/^[[:space:]]+/, "", line)
        if (cont == "") cont=line; else cont=cont " " line
        next
      }
    }
    in_fm && /^claudeSubagent:[[:space:]]*true[[:space:]]*$/ { subagent=1; next }
    in_fm && /^name:/ { v=$0; sub(/^name:[[:space:]]*/,"",v); meta["name"]=v; next }
    in_fm && /^claudeSubagentTools:/ { v=$0; sub(/^claudeSubagentTools:[[:space:]]*/,"",v); meta["tools"]=v; next }
    in_fm && /^description:/ {
      v=$0; sub(/^description:[[:space:]]*/,"",v)
      if (v ~ /^[>|][-+]?[[:space:]]*$/) { collecting="description"; cont=""; next }
      meta["description"]=v; next
    }
    !in_fm { body = body $0 "\n" }
    END {
      if (collecting != "") meta[collecting]=cont
      if (!subagent) exit 0
      name=meta["name"]
      if (name == "") exit 0
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", name)
      desc=meta["description"]
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", desc)
      tools=meta["tools"]
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", tools)
      out=out_dir "/" name ".md"
      printf "---\n" > out
      printf "name: %s\n", name >> out
      if (desc != "") printf "description: %s\n", desc >> out
      if (tools != "") printf "tools: %s\n", tools >> out
      printf "---\n" >> out
      printf "%s\n", sentinel >> out
      sub(/^\n+/, "", body)
      printf "%s", body >> out
      close(out)
      print name
    }
  ' "$skill_file"
}

# generate_subagents <agents_dir> <plugin_index_json> <names_newline_list>
# Reaps stale devkit agents, then emits a subagent for every claudeSubagent skill
# in the named plugins. Echoes one emitted agent name per line.
generate_subagents() {
  local agents_dir="$1"
  local plugin_index="$2"
  local names="$3"

  reap_devkit_agents "$agents_dir"

  local name
  while IFS= read -r name; do
    [ -z "$name" ] && continue
    local pdata skills_rel pdir skills_dir
    pdata=$(echo "$plugin_index" | jq --arg name "$name" '.[$name]')
    skills_rel=$(echo "$pdata" | jq -r '.paths.skills // empty')
    [ -n "$skills_rel" ] || continue
    pdir=$(echo "$pdata" | jq -r '._dir')
    skills_dir="$pdir/${skills_rel#./}"
    [ -d "$skills_dir" ] || continue
    local skill_md
    for skill_md in "$skills_dir"/*/SKILL.md; do
      [ -f "$skill_md" ] || continue
      grep -q "^claudeSubagent:[[:space:]]*true" "$skill_md" || continue
      mkdir -p "$agents_dir"
      emit_subagent "$skill_md" "$agents_dir"
    done
  done <<< "$names"
}
