#!/usr/bin/env bash
# Exercises the guarantee in CLAUDE.md: devkit-install deletes only files it owns
# in ~/.claude/commands and ~/.claude/output-styles, and never a user's own.
# The reap loops there run `rm -f` against the real home, so a regression in
# links_into_devkit() or the sentinel grep destroys hand-authored content.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

HOME_DIR="$TMP_DIR/home"
CMDS="$HOME_DIR/.claude/commands"
STYLES="$HOME_DIR/.claude/output-styles"
SENTINEL="<!-- devkit-managed: regenerated by devkit (do not edit) -->"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

mkdir -p "$CMDS" "$STYLES" "$TMP_DIR/elsewhere"

# 1. Hand-authored files the installer must never touch. Two shapes each: a name
# devkit knows nothing about (kept silently) and a name devkit would otherwise
# write (kept, and named in a NOTICE so the user learns why theirs won).
printf 'my own style\n' > "$STYLES/mystyle.md"
printf 'my senior override\n' > "$STYLES/senior.md"
printf 'my own command\n' > "$CMDS/mycmd.md"
printf 'my reviewer-deep override\n' > "$CMDS/reviewer-deep.md"

# 2. A symlink of the user's own, pointing outside the devkit clone.
printf 'external\n' > "$TMP_DIR/elsewhere/external.md"
ln -s "$TMP_DIR/elsewhere/external.md" "$CMDS/mylink.md"

# 3. A devkit-generated file from an earlier run: must be reaped and regenerated.
printf -- '---\ndescription: stale\n---\n\n%s\n\nstale body\n' "$SENTINEL" > "$CMDS/root-cause.md"

# 4. A devkit symlink left dangling by a moved or re-cloned devkit: must be repaired.
ln -s /gone/agentic-devkit/plugins/core/commands/wrapup.md "$CMDS/wrapup.md"

out="$TMP_DIR/install.out"
HOME="$HOME_DIR" DEVKIT_HOME_DIR="$ROOT" bash "$ROOT/bin/devkit-install" > "$out" 2>&1 \
  || fail "devkit-install exited non-zero: $(tail -3 "$out")"

[ "$(cat "$STYLES/mystyle.md")" = "my own style" ] || fail "hand-authored output style was modified or deleted"
[ "$(cat "$STYLES/senior.md")" = "my senior override" ] || fail "a user file shadowing a shipped style was overwritten"
[ "$(cat "$CMDS/mycmd.md")" = "my own command" ] || fail "hand-authored command was modified or deleted"
[ "$(cat "$CMDS/reviewer-deep.md")" = "my reviewer-deep override" ] \
  || fail "a user file shadowing a generated command was overwritten"
[ -L "$CMDS/mylink.md" ] || fail "the user's own symlink was replaced"
[ "$(readlink "$CMDS/mylink.md")" = "$TMP_DIR/elsewhere/external.md" ] \
  || fail "the user's own symlink was retargeted"

grep -qE "kept your own ~/\.claude/output-styles file\(s\) for:.*\bsenior\b" "$out" \
  || fail "no NOTICE naming the kept output style"
grep -qE "kept your own ~/\.claude/commands file\(s\) for:.*\breviewer-deep\b" "$out" \
  || fail "no NOTICE naming the kept command"

grep -qF "stale body" "$CMDS/root-cause.md" && fail "a devkit-generated command was not reaped"
grep -qF "$SENTINEL" "$CMDS/root-cause.md" || fail "the reaped command was not regenerated"

[ -e "$CMDS/wrapup.md" ] || fail "the dangling devkit symlink was not repaired"
grep -qF "Repaired: 1 broken devkit symlink" "$out" || fail "the repair was not reported"

echo "no-clobber tests passed"
